spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: worldcup7

#spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true (기본값: false)
  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
server:
  port: 5000


# MySQL FULLTEXT 인덱스로 검색하기 기능을 사용하기 위해서 DB에 직접 추가해야함
#  ALTER TABLE movie ADD FULLTEXT(title);
